jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: "sumanth"
         password: "password"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:sumanth"
        - "Overall/Read:authenticated"
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamepassword:
          scope: GLOBAL
          id: "GITHUB_CREDENTIALS_ID"
          username: "shikha-commits"
          password: ""
          description: "default credentials."
      - usernamepassword:
          scope: GLOBAL
          id: "DOCKER_HUB_ID"
          username: "sumanthksai"
          password: ""
          description: "docker credentials"
      - file:
          scope: GLOBAL
          id: "webapp-operator"
          secretBytes: ""
          description: "gke service account credentials"
          fileName: ""
      - file:
          scope: GLOBAL
          id: "webapp-operator-gcp"
          secretBytes: ""
          description: "gke service account shikha credentials"
          fileName: ""
jobs:
  - file: /var/lib/jenkins/seedJob.groovy