jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: 
         password: 
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:sumanth"
        - "Overall/Read:authenticated"
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamepassword:
          scope: GLOBAL
          id: "GITHUB_CREDENTIALS_ID"
          username: ""
          password: ""
          description: "default credentials."
      - usernamepassword:
          scope: GLOBAL
          id: "DOCKER_HUB_ID"
          username: ""
          password: ""
          description: "docker credentials"
jobs:
  - file: /var/lib/jenkins/seedJob.groovy