jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id:
         password:
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:sumanth"
        - "Overall/Read:authenticated"
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamepassword:
          scope: GLOBAL
          id: "GITHUB_CREDENTIALS_ID"
          username: "shikha-commits"
          password: "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"
          description: "default credentials."
      - usernamepassword:
          scope: GLOBAL
          id: "DOCKER_HUB_ID"
          username: "sumanthksai"
          password: "Asdqwe@5640"
          description: "docker credentials"
      - fileSecret:
            scope: GLOBAL
            id: "webapp-operator"
            secretBytes: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZWxlbWVudGFsLWljb24tNDAxMjAwIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiYjljODhhOTViMzZmNzU4MmZkZWIxM2NiYzEyZjU2MTMzNTcxMDQzMCIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFEV0hxU0FNNXhva0NGOVxuQ2pBWVI2ajFwVVFlTFd5SWpSRGxDR3RBWTNGTWF4NUd6NWxIZ0lIdFNzR0Vrc2JmRmFSb2hxYUc4SFdFMFRFUlxueURNVnZRUVRxS25uUG1YOUVVcVRudElNb01JaitWdEhrenNFVzd5TEpEQWMyYTdZeThraXRYZ2NOMHVlajhIN1xuNXJzNVkzQldGSUxLV1RPUFpVQUJpQ1RMNmFzMlNFZU1zVkgyVzNLcG1mSUc1RGxZODNtMGczZ2dBeGZLMUVpUFxuWG5MYVBPblNwZENoNFdwZ0IxZmlGSTNJTTQ0Um5rVnBtMDhKM1lDMEFqdjYvN1NCWDczcFNYNjFxSkVWbndEOFxuSHprSlN5TkE0Q2FwZlBRSktwZ1NmMXRYZGIrdmRXK1dVbGxpVHljUndRN3g4MWJQN3MxK1pML0VmQlZDVGRqSlxuQk81WmdKMjdBZ01CQUFFQ2dnRUFYMm9BTy9ERHZnU2NKN0FtaG10SWEwNWQ4R1NsZktQLzUwKzlHMUEwNkt6RFxuTFNMTlZ3TjQ0bGp4cXpZTTBOUkFFeVFOaVF3V0VqMTE5RXFXR1JYRmYwMGxpUnBSTUZoSU4wZ0txZjNwQlViVVxuMml4Tm5EK1U0UndiSklBTVhpZFJWZG92ejhNRU80QXNIU2hRUGQ2RjdKWHZRbVJGaVp6QXpPM3lGN3ZrdzZiWlxuRk1kWldpd2pKbUdPa0wxcDg4S2JkNUd1ZjhmR0F4NHBsamRyVFdGK0pGTWt4MExXNjRkbW1hbFk4cnY5YWJ0M1xuaFY3QUdVZ1VRaHI1cXFYMlZPRi9XQzBqa2dhMzErVEZDVlpLVjMxalhUZ2JEd3gwOVp6WXZacUw2Szd1NTY0RVxudTdOL2RjTTBuR0JjcjVGTUlIS25xN0U2bnVPNnZQSytqalJheXBqRzRRS0JnUUR5Q0dCOTB3NFhPUmVETDRwdFxuSm44aHlMODlBdi9HY29ybmV4M1NpbDc3aDhuZ3loOFdaWC83dURvcm1BUDdUbEVmVTQ2QlF3ZzZGNTlkR3dtSFxuY0VyYU1HbzJGeG8yanhGTFZDVm11ZDJoYnhkSkR3NkVXUHNNcHlOZW5WWDRhL3pZMXhjaVpUWkNUVHdrYWtTT1xuK3NoWTVRcThtbCtMNHh3SWh3VHlJTGdodFFLQmdRRGllZVhtbW1hRmRYS0JlWmMwcERzeVIwN0kwL1NUUmpvd1xud2czcEt0VXJTWXp0d01LNnpMY1pITVpXM0tmcEhCTXRjVElaUkw3SldCKzV3Mk5TR3FmTjd0UzdVZXYrQ2kxaFxucVArbEdQbnBnOWU2N3NPSktWQ2Z4UmZ6VFRuNWZLYmVpdGdZMjUrRWM0eHlEVUlNLzN1V3pQVWRKVW1DVVcvR1xuZ0hVNnYrTW5yd0tCZ1FDd2dxRjBRZDZOMnlvbGx4ODUrUkJRWUNudjRlY05IKzNqWVd0ZloyQmJ5aXpWVGpLYlxuejh3bGxMWi9vbTZNOFJIQ2FkcU10SWtrYktQaGI5MWtNK1d5K0FvTmhvMnNhbXd2WnArY0trTFMvOFNZbUcxNlxuNGJXOUJZdUs3ZTJMcloySnVsdDV6eHhpQUJlemF2aXkyWHdSTUlERENVWlRLMzcvVFJDelVGOVkzUUtCZ0J1dVxuSG1WQzljaldBL3JESzdIcGFMcktjRnluV3pzczJDdmhhK1hWc0Z3c0R5ZDM2ZFQrOUZvRFpGSjFnYWhDSUMzclxucWQzZ3d4akV4b3ZqejUzWFdDOFpRN0xwWGxpY1VkT2YzaThGa0hYMEFVZjlxclIyOGoyMHp5cVRnOFIwY2NpOVxuVzVBZU42N3VtSG5RR1FTUnJUOVBLWjQ0VW5XMUVsNUdrUTF2S29wTkFvR0FMYS9tajJON2FCNTFSU3NUYVdJQlxuVW1WZEJXT1J2TmNSUTNXLzJzaXhNUlVLblZWZVgwWFdoN1hzc0E1V1dlVkxRS2JEWVdYelAxVHY2M2R4a2ZmMVxuZWV4Smp0Z0J1SzVseGpLaEJvM3Bta3dXM0ZJUE8va1IxTjhTRzMwZ1h2NUlVaUNwYWxDcFVMOW14QW9BMHFSY1xuRkZjTkNIS1RZM2hwbDQ1TzQzOW9LaU09XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiZGV2LXNlcnZpY2UtYWNjb3VudEBlbGVtZW50YWwtaWNvbi00MDEyMDAuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTE0NDY1NjA0NjE0NDI5NTA5Mjc4IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9kZXYtc2VydmljZS1hY2NvdW50JTQwZWxlbWVudGFsLWljb24tNDAxMjAwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9Cg==
            fileName: "webapp-operator-key.json"
            description: "Webapp Operator Credential"

jobs:
  - file: /var/lib/seedJob.groovy