jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN}
         password: ${JENKINS_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:${JENKINS_ADMIN}"
        - "Overall/Read:authenticated"
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamepassword:
          scope: GLOBAL
          id: "GITHUB_CREDENTIALS_ID"
          username: "${{ secrets.username }}"
          password: "${{ secrets.personalAccessToken }}"
          description: "default credentials."
      - usernamepassword:
          scope: GLOBAL
          id: "DOCKER_HUB_ID"
          username: "${{ secrets.docker_username }}"
          password: "${{ secrets.docker_password }}"
          description: "docker credentials"
jobs:
  - file: /var/lib/jenkins/seedJob.groovy                                                                                                                                  21,5          Top
