# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Packer-Jenkins CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    #environment: sumanth
    steps:
    - uses: actions/checkout@v3
      env:
        aws_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
    - name: Use the aws key
      run: |
          echo "Using API key: $aws_key"
    - name: AWS configuration
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region: us-east-1
    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"
    - name: Run `packer init`
      id: init
      run: "packer init aws-ami.pkr.hcl"
    - name: Run `packer build`
      id: build
      run: "packer build aws-ami.pkr.hcl"

